100-process_and_pid_file

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Write the script's PID to /var/run/myscript.pid
 
-echo $$ > /var/run/myscript.pid
+echo "$$" > /var/run/myscript.pid
 # Function to clean up and terminate the script
 cleanup_and_exit() {
     # Remove the PID file
@@ -12,6 +12,8 @@ cleanup_and_exit() {
 # Set traps for different signals
 trap 'echo "I hate the kill command"' SIGTERM  # Custom response for SIGTERM
 trap 'echo "Y U no love me?!"; exit 0' SIGINT  # Custom response for SIGINT with immediate exit
+trap cleanup_and_exit SIGQUIT  # Cleanup and exit for SIGQUIT
+trap cleanup_and_exit SIGTERM  # Cleanup and exit for SIGTERM
 
 # Infinite loop that outputs a message every 2 seconds
 while true; do
